### ISSUE TITLE
Port cyclcing doesn't seem to work still.\

### ISSUE THREAD

**Issue by RangerMauve** [datproject/hyperdiscovery#35]
@DeltaF1 had an issue using the Dat SDK in two processes. https://github.com/datproject/sdk/issues/8

It would throw a `Error: Could not bind` exception on the UTP socket.

**Comment by DeltaF1** [comment]
I was unable to replicate the issue on a different computer running WSL, so it might be some weird UTP-native bug on my laptop 🤔

**Comment by RangerMauve** [comment]
Weird. I guess we can close this until it's reproducible again. :P

**Comment by DeltaF1** [comment]
Still not sure why I was unable to reproduce on my desktop, I will update here if I ever figure out why :)
