### ISSUE TITLE
How to get the ARCHIVE_KEY?

### ISSUE THREAD

**Issue by tiandiyiqi** [datproject/hyperdiscovery#38]
“Run the following code in two different places and they will replicate the contents of the given ARCHIVE_KEY”
How to get the ARCHIVE_KEY?

**Comment by RangerMauve** [comment]
@tiandiyiqi are you looking for an existing archive to test with? You can try my blog's key if you want.

```
const ARCHIVE_KEY = Buffer.from('0a9e202b8055721bd2bc93b3c9bbc03efdbda9cfee91f01a123fdeaadeba303e', 'hex')
```
